### ISSUE TITLE
Not Really an Issue but...

### ISSUE THREAD

**Issue by dercavendar** [scraton/node-red-contrib-plex-ws#2]
I really like this project but I wanted to make a feature request.  I'm new on github so I don't know the protocol on how to do that so here I am.  What I would like to be able to do is use the genre tag as a filter so that i can set up my lights based on the genre I am watching.  I'm not the greatest programmer in the world but i did look at the source code and in the playing.html it has the list of filterable keys and I was wondering if all that was needed to accomplish this would be to add Genre.tag as a filterable key.  I tried this but it didn't seem to work.  Any ideas if this is even a possible use case?

**Comment by scraton** [comment]
Hi there!

That's a neat idea! Unfortunately I don't believe the tags are sent over the websocket protocol when media is being played. At least that isn't the case on my version of Plex. Are you seeing differently?

It would be possible to fetch that data when the media is being played, but it's not as easy as adding "Genre.tag" to playing.html unfortunately. If it were any other key already there, you would be correct to do that, though.

I'll try and do some tinkering in the near future to see what would be necessary to pull that data and include it in the node's payload.

**Comment by dercavendar** [comment]
I actually came up with a semi-solution for this that should work for me (i'm away from home so i cant try just yet).  In the msg.session there is an object for genre with the applicable tags so I can set up a switch node to act as the filter and end up with the same end results (in theory).  I would just set up a playing node with a switch that would route based on msg.session.genre.tag == horror action etc.  and move from there to my lights

**Comment by scraton** [comment]
Oh, I see the `Genre` field now. I guess it's only enabled for movies?

Since it's part of the payload, the switch node probably could have handled it. So good idea there! Though I'm unsure if it supports arrays, which `Genre.tag` would be.

Anyway I had some time tonight to take a stab at implementing it. I've added both `Genre.tag` and `Genre.id` as filterable options. If any of the genres match the text you type in, it will match the filter. So if you have the genre tags of `['Animation', 'Drama', 'Horror']` and set a filter for `== Animation`, it will match.

This is in 0.2.0 which should be available via the palette manager shortly. Let me know if you have any issues with it. :)

**Comment by dercavendar** [comment]
This works like a charm for what I had in mind.  Just one thing to note is that because TV shows do not have genre info it does end up sending out an error message (failed to fetch session details from plex: TypeError: Cannot read property 'tag' of undefined) when watching a tv show, but this is not a problem for me just a heads up for if someone else mentions it.
